#!/usr/bin/env bash
# a bash script that installs Nginx server.
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"
sudo chown $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
