#!/usr/bin/env bash
# a bash script that installs Nginx, creates a cutsom 404 page, and redirects the /redirect_me path.

sudo apt-get update -y
sudo apt-get install nginx -y

sudo sed -i "/listen 80 default_server;/a add_header X-Served-By $(hostname);" /etc/nginx/sites-enabled/default
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.linkedin.com/in/abenetg permanent;" /etc/nginx/sites-enabled/default

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
sudo sed -i "37i error_page 404 /404.html;\n location = /404.html {\n root /var/www/html;\n internal;\n}" /etc/nginx/sites-enabled/default

sudo service nginx restart
