#!/usr/bin/env bash
# a bash script that fixes Nginx server that fails to listen on port 80.
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
