#!/usr/bin/env bash
# a script that fixes Nginx server that failed to listen on port 80.
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
kill "$(pgrep 'nginx' | head -1)"
